services:
  - type: web
    name: google-ads-negatif-kelime
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEVELOPER_TOKEN
        sync: false
      - key: GOOGLE_ADS_CLIENT_ID
        sync: false
      - key: GOOGLE_ADS_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ADS_REFRESH_TOKEN
        sync: false
      - key: LOGIN_CUSTOMER_ID
        sync: false
      - key: APP_PASSWORD
        sync: false
